# Generated by Django 5.0.7 on 2024-09-10 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('allDay', models.BooleanField(default=False)),
                ('task', models.CharField(max_length=30)),
                ('project', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('projId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetracker.project')),
            ],
            options={
                'db_table': 'Events',
            },
        ),
        migrations.CreateModel(
            name='ProjectSlackChannelMapEntry',
            fields=[
                ('channel_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetracker.project')),
            ],
        ),
    ]
