# Generated by Django 5.0.7 on 2024-09-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='task',
        ),
    ]
