# Generated by Django 5.0.7 on 2024-10-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateevents',
            name='day',
        ),
    ]
