# Generated by Django 5.0.6 on 2024-10-10 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0002_delete_projectslackchannelmapentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'Template',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='billable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='TemplateEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('day', models.CharField(default='', max_length=9)),
                ('billable', models.BooleanField(default=True)),
                ('templateId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetracker.template')),
            ],
            options={
                'db_table': 'TemplateEvents',
            },
        ),
    ]
