# Generated by Django 5.0.7 on 2024-08-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetracker", "0002_rename_description_events_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="end",
            field=models.DateField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="events",
            name="isAllDay",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="events",
            name="start",
            field=models.DateField(blank=True, default=None, max_length=50),
        ),
    ]
