# Generated by Django 5.0.7 on 2024-09-13 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0002_remove_events_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='projId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timetracker.project'),
        ),
    ]
