# Generated by Django 5.0.7 on 2024-10-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0002_remove_templateevents_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateevents',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='templateevents',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
