# Generated by Django 5.0.7 on 2024-09-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0003_alter_events_projid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='project',
        ),
    ]
