# Generated by Django 5.0.6 on 2024-10-10 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0003_template_events_billable_templateevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateevents',
            name='projectId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetracker.project'),
        ),
    ]
