# Generated by Django 5.0.7 on 2024-08-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetracker", "0004_alter_events_end_alter_events_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="events",
            name="start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
