# Generated by Django 5.0.7 on 2024-08-06 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timetracker", "0005_alter_events_end_alter_events_start"),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="isAllDay",
            new_name="allDay",
        ),
    ]
