# Generated by Django 5.0.7 on 2024-10-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0005_alter_templateevents_end_alter_templateevents_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='billable',
        ),
    ]
