# Generated by Django 5.0.7 on 2024-09-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0006_alter_events_projid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
