# Generated by Django 5.0.7 on 2024-08-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetracker", "0006_rename_isallday_events_allday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="events",
            name="allDay",
        ),
        migrations.RemoveField(
            model_name="events",
            name="end",
        ),
        migrations.RemoveField(
            model_name="events",
            name="start",
        ),
        migrations.AddField(
            model_name="events",
            name="times",
            field=models.JSONField(default=list),
        ),
    ]
