# Generated by Django 5.0.7 on 2024-09-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0008_rename_projid_events_projectid_alter_project_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='projectId',
            new_name='projectID',
        ),
    ]
