# Generated by Django 5.0.7 on 2024-08-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0009_user_events_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='user',
        ),
        migrations.RemoveField(
            model_name='events',
            name='times',
        ),
        migrations.AddField(
            model_name='events',
            name='allDay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='project',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='events',
            name='task',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
