# Generated by Django 5.0.6 on 2024-09-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0009_rename_projectid_events_projectid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='Project',
        ),
    ]
