# Generated by Django 5.1 on 2024-09-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0010_alter_project_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='origin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
