# Generated by Django 5.0.7 on 2024-09-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0010_alter_project_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='resourceID',
            field=models.CharField(default='localEvents', max_length=20),
        ),
    ]
