# Generated by Django 4.2.1 on 2024-08-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0010_remove_events_user_remove_events_times_events_allday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=256)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='project',
            field=models.CharField(max_length=64),
        ),
    ]
