# Generated by Django 5.0.7 on 2024-09-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0011_events_resourceid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='projectID',
            new_name='projectId',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='resourceID',
            new_name='resourceId',
        ),
    ]
