# Generated by Django 5.1 on 2024-09-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0012_alter_events_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='origin',
            field=models.IntegerField(default=0),
        ),
    ]
