# Generated by Django 5.1 on 2024-09-10 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0012_remove_project_end_remove_project_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='projId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetracker.project'),
        ),
        migrations.CreateModel(
            name='ProjectSlackChannelMapEntry',
            fields=[
                ('channel_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetracker.project')),
            ],
        ),
    ]
