# Generated by Django 5.0.7 on 2024-09-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0012_alter_events_origin'),
        ('timetracker', '0012_rename_projectid_events_projectid_and_more'),
    ]

    operations = [
    ]
