# Generated by Django 5.0.7 on 2024-09-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0013_merge_20240921_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='allDay',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='origin',
            field=models.IntegerField(default=0),
        ),
    ]
