# Generated by Django 5.0.7 on 2024-09-24 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0014_alter_events_allday_alter_events_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='events',
            name='resourceId',
        ),
    ]
