name: React CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Load Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install deps
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build
